# Generated by Django 4.0 on 2022-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_book_category_alter_borrowedbook_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
