# Generated by Django 4.1 on 2022-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='number_visits',
            field=models.SmallIntegerField(default=1),
        ),
    ]
